### ISSUE TITLE
LogsExecutor in TestActivity.java not found

### ISSUE THREAD

**Issue by RKuanysh** [YouTransactor-SAS/mPOS-SDK-Android#4]
I have downloaded the latest version of the project and LogsExecutor cannot be found when building.
Could you please address this issue?

`mPOS-SDK-Android/sampleapp/src/main/java/com/youtransactor/sampleapp/test/TestActivity.java:94: error: cannot find symbol
        runLogsBt.setOnClickListener(v -> LogsExecutor.runLogs(this));
                                          ^
  symbol:   variable LogsExecutor
  location: class TestActivity`

**Comment by YouTransactor** [comment]
Hi, 

Sorry about that I forget to add two new files. 
It should be good now. 

Thanks

**Comment by YouTransactor** [comment]
I close the issue as it was resolved.
